#!/usr/bin/env bash
set -e
BASE_DIR="$(dirname "$0")/.."
TMP_DIR="$BASE_DIR/tmp"
ENV_FILE="$TMP_DIR/.env"
mkdir -p "$TMP_DIR"

# Exit if env file already exists
if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists, skipping VAPID key generation."
  exit 0
fi

echo "Generating VAPID keys..."
keys=$(npx --yes web-push generate-vapid-keys --json)
publicKey=$(echo "$keys" | node -e "console.log(JSON.parse(require('fs').readFileSync(0, 'utf-8')).publicKey)")
privateKey=$(echo "$keys" | node -e "console.log(JSON.parse(require('fs').readFileSync(0, 'utf-8')).privateKey)")

cat <<EOF > "$ENV_FILE"
# THIS FILE IS AUTOMATICALLY GENERATED AT FIRST DEVCONTAINER INITIALIZATION.
# DO NOT MODIFY OR DELETE THIS FILE.
# CHANGES WON'T TAKE EFFECT WHILE CONTAINERS EXIST (EVEN IF STOPPED)
# AND MAY BREAK KEY SYNCHRONIZATION BETWEEN FRONTEND AND BACKEND.
NOTIFICATION_PUBLIC_KEY=$publicKey
NOTIFICATION_PRIVATE_KEY=$privateKey
WHISPER_VAPID_KEY=$publicKey
EOF

echo ".env file created with VAPID keys."